### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RemcoPl** [hexosse/AddLight#32]
If i use the plugin
25.02 21:42:28 [Server] ERROR Could not pass event PlayerInteractEvent to AddLight v4.3.2
25.02 21:42:28 [Server] INFO org.bukkit.event.EventException: null
25.02 21:42:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:944) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
25.02 21:42:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
25.02 21:42:28 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
25.02 21:42:28 [Server] INFO at com.github.hexocraft.addlight.integrations.WorldEditHooker.isLocationInSelection(WorldEditHooker.java:99) ~[?:?]
25.02 21:42:28 [Server] INFO at com.github.hexocraft.addlight.LightsApi.removeLight(LightsApi.java:214) ~[?:?]
25.02 21:42:28 [Server] INFO at com.github.hexocraft.addlight.listeners.PlayerListener.onPlayerInteract(PlayerListener.java:144) ~[?:?]
25.02 21:42:28 [Server] INFO at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source) ~[?:?]
25.02 21:42:28 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
25.02 21:42:28 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
25.02 21:42:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
25.02 21:42:28 [Server] INFO ... 17 more

**Comment by RemcoPl** [comment]
I found the error and a fix in the other ones
